services:

  # PostgreSQL
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db-network

  # Interface web PostgreSQL (optionnel)
  pgadmin:
    image: dpage/pgadmin4:9.13
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_WEB_MAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_WEB_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8082:80"
    volumes:
      - ./pgadmin-config/servers.json:/pgadmin4/servers.json
      - ./pgadmin-config/pgpassfile:/tmp/pgpassfile
    depends_on:
      - postgres
    networks:
      - db-network

volumes:
  postgres_data:

networks:
  db-network:
    driver: bridge
